var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/03_fabrication/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8a92aa77._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_e11ff72b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a30af444._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d8ef6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_03_fabrication_page_actions_8c6e2c99.js")
R.m(24412)
module.exports=R.m(24412).exports
