import type { Metadata } from "next";
import Link from "next/dist/client/link";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import "./style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Alice Liu PS70: Intro to Digital Fabrication </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="./style.css" rel="stylesheet" />
        <script src="./strapdown.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>
      </head>

      <body>
        <nav className="navbar navbar-expand-sm navbar-dark" style={{backgroundColor: '#dcdcdc', color: '#EEE7E8'}}>
          <div style={{alignItems: 'center', justifyContent: 'center'}} className="container-fluid">
            <div className="flexrow">
              <h2 className="nav-title">PS70 Spring 2026</h2>
            </div>
            <div className="navbar-nav">
              <h4><Link className="nav-link" href="./">Home</Link></h4>
              <h4><Link className="nav-link" href="./about">About</Link></h4>
              <h4><Link className="nav-link" href="./13_finalproject">Final Project</Link></h4>
            </div>
          </div>
        </nav>
        {children}
      </body>
      
    </html>
  );
}
