var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/01_intro/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b04476bd._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_5cb9ad25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a30af444._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d8ef6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_01_intro_page_actions_6f932fac.js")
R.m(99742)
module.exports=R.m(99742).exports
