// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/01_intro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/01_intro">> = Specific
  const handler = {} as typeof import("../../../app/01_intro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/02_2Ddesign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/02_2Ddesign">> = Specific
  const handler = {} as typeof import("../../../app/02_2Ddesign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/03_fabrication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/03_fabrication">> = Specific
  const handler = {} as typeof import("../../../app/03_fabrication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/04_microcontroller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/04_microcontroller">> = Specific
  const handler = {} as typeof import("../../../app/04_microcontroller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/05_3Ddesign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/05_3Ddesign">> = Specific
  const handler = {} as typeof import("../../../app/05_3Ddesign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/06_inputs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/06_inputs">> = Specific
  const handler = {} as typeof import("../../../app/06_inputs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/07_outputs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/07_outputs">> = Specific
  const handler = {} as typeof import("../../../app/07_outputs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/08_cnc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/08_cnc">> = Specific
  const handler = {} as typeof import("../../../app/08_cnc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/09_networking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/09_networking">> = Specific
  const handler = {} as typeof import("../../../app/09_networking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/10_machine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/10_machine">> = Specific
  const handler = {} as typeof import("../../../app/10_machine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/13_finalproject/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/13_finalproject">> = Specific
  const handler = {} as typeof import("../../../app/13_finalproject/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
