var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/04_microcontroller/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__20000e52._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_6fc285c5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a30af444._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d8ef6eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_04_microcontroller_page_actions_56d2813e.js")
R.m(53928)
module.exports=R.m(53928).exports
